[package]
name = "congregation_notice_board"
version = "0.1.0"
edition = "2024"

[dependencies]
bcrypt = "0.17.0"
dotenv = "0.15.0"
jsonwebtoken = "9.3.1"
multipart = "0.18.0"
once_cell = "1.21.3"
rusqlite = "0.35.0"
serde = { version = "1.0.219", features = ['derive'] }
serde_json = "1.0.140"
